import json
import textwrap

class Generator:
    """
    Translates a Builder Flow (JSON) into a Python script.
    """

    @staticmethod
    def generate_code(flow_data: str, name: str, description: str) -> str:
        # 1. Extract inputs for the class attribute
        data = json.loads(flow_data)
        nodes = data.get("nodes", [])
        
        inputs_schema = []
        for node in nodes:
            if node["type"] == "input_external":
                d = node.get("data", {})
                inputs_schema.append({
                    "name": d.get("name"),
                    "label": d.get("label") or d.get("name"),
                    "type": d.get("type", "text"),
                    "default": d.get("default"),
                    "required": d.get("required", False)
                })

        # 2. Build the Python script string
        code = f'''\
"""
Autogenerated Scraper from Builder Flow
"""
import json
from typing import List, Dict, Any
from app.scrapers.base import BaseScraper
from app.builder.engine import BuilderEngine

class GeneratedScraper(BaseScraper):
    name = "{name}"
    description = "{description or 'ScrapeTL Builder Flow'}"
    
    # Declarative inputs for the UI
    inputs = {json.dumps(inputs_schema, indent=8)}

    def scrape(self, vars=None, db=None, **kwargs) -> List[Dict[str, Any]]:
        """
        Executes the builder DAG flow.
        """
        flow_data = {json.dumps(data)}
        
        # Initialize the engine
        engine = BuilderEngine(
            flow_data=flow_data,
            global_vars=vars or {{}},
            db_session=db
        )
        
        # Run execution
        results = engine.execute(runtime_inputs=kwargs)
        
        # Persist debug info for the runner to collect
        self.debug_payload = getattr(engine, "_debug_info", [])
        
        return results
'''
        return code
