"""
Autogenerated Scraper from Builder Flow
"""
import json
from typing import List, Dict, Any
from scrapetl import BaseScraper
from scrapetl.builder.engine import BuilderEngine

class GeneratedScraper(BaseScraper):
    name = "ABC"
    description = "ScrapeTL Builder Flow"
    
    # Declarative inputs for the UI
    inputs = []

    def scrape(self, vars=None, db=None, **kwargs) -> List[Dict[str, Any]]:
        """
        Executes the builder DAG flow.
        """
        flow_data = {"nodes": [{"id": 1774912001856, "x": 2200, "y": 2200, "type": "input", "preset": "expression", "config": {"value": "https://erascans.com/manga/revenge-of-the-iron-blooded-sword-hound/"}}, {"id": 1774912015544, "x": 2520, "y": 2160, "type": "action", "preset": "fetch_url", "config": {"headers": "{     \"User-Agent\": (         \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"         \"AppleWebKit/537.36 (KHTML, like Gecko) \"         \"Chrome/123.0 Safari/537.36\"     ),     \"Accept-Language\": \"en-US,en;q=0.9\", }"}}, {"id": 1774912076949, "x": 2820, "y": 2220, "type": "sink", "preset": "system_output", "config": {"label": "Results1"}}], "edges": [{"from": 1774912001856, "fromIdx": 0, "to": 1774912015544, "toIdx": 0}, {"from": 1774912015544, "fromIdx": 0, "to": 1774912076949, "toIdx": 0}], "config": {"viewport": {"x": -1994, "y": -1999, "zoom": 1}}}
        
        # Initialize the engine
        engine = BuilderEngine(
            flow_data=flow_data,
            global_vars=vars or {},
            db_session=db
        )
        
        # Run execution
        results = engine.execute(runtime_inputs=kwargs)
        
        # Persist debug info for the runner to collect
        self.debug_payload = getattr(engine, "_debug_info", [])
        
        return results

GeneratedScraper().scrape()